### ISSUE TITLE
createFromUrl does not cleanup local files (disk usage problem)

### ISSUE THREAD

**Issue by andjoen** [datocms/js-rest-api-clients#25]
I'm using `@datocms/cma-client-node` to import images to DatoCMS on a schedule. Specifically using the `createFromUrl`-function like this:

```ts
client.uploads.createFromUrl({
    url: '<url>',
    skipCreationIfAlreadyExists: true,
});
```

After letting the import run on schedule for a while, I have observed that this fills up the disk rather quickly since the `createFromUrl`-function does not cleanup the temp-files after successful upload.

I have solved this by emptying the `/tmp`-directory manually but it would be nice if the client would do this automatically.

Suggestion: maybe run the `deleteFile`-function after upload result?

```ts
// Upload.ts
//...
runningPromise = this.createFromLocalFile({
  localPath: filePath,
  onProgress,
  ...other,
});

const result = await runningPromise;

// Add this line?
await deleteFile();
//...
```

**Comment by stefanoverna** [comment]
Thank you for the report! Fixed in v3.1.8!
