### ISSUE TITLE
cma-client-node: passing environment to client returns 404

### ISSUE THREAD

**Issue by colinhowells** [datocms/js-rest-api-clients#4]
using `@datocms/cma-client-node` i get a 404 back when adding an environment property. leaving that out works fine (which sends to the primary env).

looking at the response headers the `x-environment` is correct ... but it may be i'm goofing something up, not sure what.

```js
 // listening here for a script argument eg 'npm run import --env=develop'
const devEnv = process.env?.npm_config_env || null;
let clientConfig = {
	apiToken: process.env.DATO_CONTENT_MANAGEMENT_API_TOKEN,
};
if (devEnv) clientConfig.environment = devEnv;
const client = buildClient(clientConfig);
```
here's a response in case the `x-request-id` and error ID are useful:

```
response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'access-control-allow-credentials': 'true',
      'access-control-allow-headers': 'authorization, content-type, x-environment, x-site-domain, x-api-version, user-agent, x-session-id, x-include-drafts, x-exclude-invalid',
      'access-control-allow-methods': 'GET, POST, PUT, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'x-ratelimit-limit, x-ratelimit-remaining, x-ratelimit-reset',
      'access-control-max-age': '1728000',
      'cache-control': 'no-cache',
      'cf-cache-status': 'DYNAMIC',
      'cf-ray': '74eefe4a48bbc5a8-SEA',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 22 Sep 2022 23:59:16 GMT',
      'referrer-policy': 'strict-origin-when-cross-origin',
      server: 'cloudflare',
      'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept,Accept-Encoding',
      via: '1.1 vegur',
      'x-api-version': '3',
      'x-content-type-options': 'nosniff',
      'x-download-options': 'noopen',
      'x-environment': 'develop',
      'x-frame-options': 'SAMEORIGIN',
      'x-permitted-cross-domain-policies': 'none',
      'x-queue-time': '0ms',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '59',
      'x-request-id': '356b6c77-0d5c-4c4e-a08b-6ea02b69b901',
      'x-runtime': '0.028444',
      'x-xss-protection': '1; mode=block'
  },
  body: {
      data: [
        {
          id: '302048',
          type: 'api_error',
          attributes: { code: 'NOT_FOUND', details: {} }
        }
      ]
  }  
}
```

**Comment by stefanoverna** [comment]
What is the specific call you're making, that returns NOT_FOUND? A complete example that reproduces the issue would be great, thanks!

**Comment by colinhowells** [comment]
i did some testing and guessed it might be because my primary environment hadn't been forked in a long time. i created a new fork, `client.items.create()`d items in there, and everything works fine.

so my guess is: the 404 wasn't due to the endpoint, or the environment name not existing, or the item-type IDs being different between environments (they were, and i'd been handling that, but this new fork has identical item-type IDs), but a discrepancy (which i couldn't track down) in the content models between environments? not sure, given that the error message doesn't tell us what exactly isn't found – but it's a good reminder to keep forking the primary to keep things up to date.

**Comment by colinhowells** [comment]
in case it wasn't clear before, you can close this out, i have no outstanding questions and whatever issue there was was cleared up by me re-forking my primary environment ... thanks again.
