### ISSUE TITLE
Client throws error in javascript console for each call

### ISSUE THREAD

**Issue by rumtraubenuss** [datocms/js-rest-api-clients#5]
Using `@datocms/cma-client-browser` `v1.1.8` in a dato plugin. Any call with the client throws an error in the javascript console:
```
Refused to set unsafe header "user-agent" browser-ponyfill.js:504
```
The data fetching/mutating is working though.
It is happening at least when running the plugin locally (did not publish or deployed the plugin so far).
Tested in Chrome Version 106.0.5249.119 (Official Build) (arm64).

**Comment by stefanoverna** [comment]
v1.1.10 should solve the warning, thanks for reporting!
