### ISSUE TITLE
v. 1.1.22 - @datocms/cma-client-browser not working with the latest expo SDK (React Native)

### ISSUE THREAD

**Issue by mkidawa** [datocms/js-rest-api-clients#7]
Hello,
I have been using  `@datocms/cma-client-browser` for some time now with Expo SDK 45, but after updating to the newest 47 version, builds started failing giving the following error:
`TypeError: undefined is not an object (evaluating 'navigator.userAgent.includes')`
I'm not sure whether userAgent is even present by default in the React Native Expo environment but somehow it was working previously.

package version: 1.1.22

Would appreciate help 😄

**Comment by stefanoverna** [comment]
Hi @mkidawa can you provide a stacktrace?

**Comment by mkidawa** [comment]
@stefanoverna unfortunately Native stack trace is very poor and this is the only data I was able to capture

<img width="397" alt="Zrzut ekranu 2023-01-30 o 13 51 56" src="https://user-images.githubusercontent.com/37329984/215482287-0cfe8670-e77e-4979-a8f3-4eb311db9e98.png">

Downgrading to expo 45 and running the latest lib version also produces this error, so this is not an expo version related issue.

**Comment by mkidawa** [comment]
@stefanoverna after some time of debugging I have discovered that this is an issue with `rest-client-utils`. After downgrading this particular package problem disappeared. Might be a valuable clue 😄 
What is more I have noticed that urls were constructed the wrong way. Let's say I want to access all items from the `health_hub_article` model.
The request should be `https://site-api.datocms.com/items?filter%5Btype%5D=health_hub_article` but instead it creates `https://site-api.datocms.com/items?0=filter%5Btype%5D%2Chealth_hub_article`

**Comment by stefanoverna** [comment]
@mkidawa which past version resolves the issue?

**Comment by stefanoverna** [comment]
We should have fixed the issue with `@datocms/rest-client-utils@1.2.2`!

**Comment by mkidawa** [comment]
@stefanoverna I have updated cma-client to the newest version (1.2.2), but the problem with wrong URL creation stil persists.
Example of a malformed URL:
`https://site-api.datocms.com/items?0=filter%5Btype%5D%2Chealth_hub_article&1=page%5Blimit%5D%2C5&2=page%5Boffset%5D%2C0&3=order_by%2C_published_at_DESC`
Downgrading to 1.0 fixed this issue.

**Comment by stefanoverna** [comment]
@mkidawa the problem probably is around here: https://github.com/datocms/js-rest-api-clients/blob/main/packages/rest-client-utils/src/buildNormalizedParams.ts

Can you paste the exact call you're performing to the client? Thank you!

**Comment by matjack1** [comment]
hello @mkidawa I'm closing this as maybe you are not interested anymore. But if you still need help on this, please reopen.
